<?xml version="1.0"?>
<package format="2">
  <name>beetle_omni</name>
  <version>1.0.0</version>
  <description>The beetle_omni package</description>

  <maintainer email="jinjie-li@dragon.t.u-tokyo.ac.jp">LI, Jinjie</maintainer>
  <license>BSD</license>
  <url type="website">https://github.com/jsk-ros-pkg/jsk_aerial_robot</url>
  <author email="jinjie-li@dragon.t.u-tokyo.ac.jp">LI, Jinjie</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>std_srvs</build_depend>
  <build_depend>aerial_robot_control</build_depend>
  <build_depend>aerial_robot_model</build_depend>
  <build_depend>aerial_robot_estimation</build_depend>
  <build_depend>aerial_robot_msgs</build_depend>
  <build_depend>pluginlib</build_depend>
  <build_depend>diagnostic_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>spinal</build_depend>
  <build_depend>takasako_sps</build_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>aerial_robot_control</exec_depend>
  <exec_depend>aerial_robot_model</exec_depend>
  <exec_depend>aerial_robot_msgs</exec_depend>
  <exec_depend>aerial_robot_estimation</exec_depend>
  <exec_depend>aerial_robot_simulation</exec_depend>
  <exec_depend>aerial_robot_base</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>pluginlib</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>spinal</exec_depend>
  <exec_depend>takasako_sps</exec_depend>

  <test_depend>rostest</test_depend>

  <export>
    <aerial_robot_control plugin="${prefix}/rlagent_plugins.xml" />
  </export>
</package>
