aerial_robot_control_name: aerial_robot_control/beetle_pose_rlagent
########################################################################
# Trajectory Tracking initial pose:
# python scripts/rl/pub_desired_pose.py 0.0 0.0 0.7 0 0 0 




# policy-2025-12-06_16-55-18-20000.onnx # ideal obs
# policy-2025-12-12_10-32-54-10000.onnx # 1. deploy: current best in sim, z osscilation in real
# policy-2025-12-16_22-57-33-20000.onnx # 2. add thrust cmd delay, more stable, z osscilation is less
# policy-2025-12-18_22-46-06-20000.onnx # 3. (remove gravity, change scales) stable in nozero roll/pitch but osscilation in hovering 
# policy-2025-12-19_21-00-13-39000.onnx # 4. gravity curriculum
# policy-2025-12-22_22-43-28-46000.onnx #
# policy-2025-12-26_12-54-59-50000.onnx # emhanced normal flight
# policy-2025-12-26_22-58-28-46000.onnx # fault tolerant
# policy-2026-01-04_14-47-50-18000.onnx # oscilation during 45 Roll
# New Observation Sequence:
# policy-2026-01-06_13-52-36-18000.onnx # maybe deploy
# policy-2026-01-08_14-21-53-12000.onnx # (basic) looks nice, deploy, obcilation in vertical z
# policy-2026-01-08_14-37-39-12000.onnx # (basic with fault) maybe deployS

# policy-2026-01-09_20-11-41-20000.onnx # (hovering) benchmark, can be used to test platform
# policy-2026-01-09_21-07-56-17000.onnx # basic based on benchmark
# New velocity reward
# policy-2026-01-11_18-11-25-16000.onnx # (slow)

# policy-2026-01-15_18-05-16-20000.onnx # basic task for benchmark
# policy-2026-01-16_11-07-06-21000.onnx # verybad

# policy-2026-01-18_19-46-02-32000.onnx # base
# benchmark => different scheme
# policy-2026-01-18_14-58-28-20000.onnx # change vel reward (gimbal oscillation)
# policy-2026-01-18_15-11-36-20000.onnx # add align gimbal (little gimbal oscillation, danger tilt !)
# policy-2026-01-18_15-17-44-20000.onnx # add init vel (little gimbal oscillation, danger tilt !)
# policy-2026-01-18_15-33-42-20000.onnx # thrust power reward 1e-5 => 5e-5
# policy-2026-01-19_11-21-32-9000.onnx

# policy-2026-01-20_22-37-31-20000.onnx # want to try deploy
# policy-2026-01-20_22-37-31-26000.onnx
# policy-2026-01-20_22-37-31-32000.onnx

# 2026-01-25 try to deploy models:
# policy-2026-01-22_22-08-43-20000.onnx; 19000, 18000, 16000
# policy-2026-01-24_22-40-44-20000.onnx; 18000, 16000, try
# policy-2026-01-24_22-47-24-20000.onnx; 18000, 16000, try
# policy-2026-01-24_22-59-35-20000.onnx; cannot flip
# policy-2026-01-24_23-16-56-20000.onnx; cannot flip, danger
# policy-2026-01-24_23-16-56-40000.onnx; give up

# policy-2026-01-23_20-34-47-20000.onnx
# policy-2026-01-23_20-34-47-18000.onnx

# policy-2026-01-23_20-34-47-18000.onnx
# policy-2026-01-22_22-08-43-20000.onnx

# policy-2026-03-02_11-45-01-20000.onnx based on benchmark with beetle-rl urdf
# policy-2026-03-04_22-25-52-20000.onnx se3 env
# policy-2026-03-05_11-02-19-20000.onnx Omni env
# policy-2026-03-05_22-29-42-20000.onnx regoal with large vel penalty
# policy-2026-03-06_13-37-13-16000.onnx regoal and random gimbal

rlagent:
  onnx_model_path: "policy/policy-2026-03-06_13-37-13-16000.onnx" # Path in ros package
  control_freq: 400.0
  decimation: 2
  history_obs: false
  single_obs_size: 27
  history_length: 4
  fault_injection: false
  fault_obs: false
  fault_goal: false  # degraded goal when fault injected
  ideal_obs: false
  ideal_obs_topic: "uav/cog/odom"
  ideal_delay: 0
  fc2root_transform: true # general, in estimator, baselink is set as fc frame (IMU), while the policy is trained with base_link as reference (Geometry Center )
  rlagent_verbose: false
  rlagent_debug: true
  rlagent_forward_info: true
  gimbal_target_delay_steps: 0
  gimbal_obs_delay_steps: 0
  enable_thrust: true
  thrust_scale: 1.0
  thrust_tau: 0.0
  thrust_target_delay_steps: 0
  enable_gimbal: true
  goal_pos_x: 0.0
  goal_pos_y: 0.0
  goal_pos_z: 0.7
  goal_angle_R: 0.0
  goal_angle_P: 0.0
  goal_angle_Y: 0.0
  thrust_default: 7.0 # 6.0 before 3.
  thrust_limit: 20.0
  gimbal_default: {gimbal1: 0.0, gimbal2: 0.0, gimbal3: 0.0, gimbal4: 0.0}
  gimbal_kp: 0.344964875
  gimbal_kd: 0.0094725 # 
  gimbal_effort_ctrl: false
  gimbal_size: 4
  thrust_size: 4
  scales:
    lin_vel: 1.0
    agn_vel: 0.2
    gimbal_act: 0.25
    thrust_act: 0.50  # 1.25 before 3.
    clip_observation: 100.0
    clip_action: 100.0