aerial_robot_control_name: aerial_robot_control/beetle_pose_rlagent
# policy-2025-12-06_16-55-18-20000.onnx ideal obs
# policy-2025-12-12_10-32-54-10000.onnx # current best
# policy-2025-12-16_22-57-33-20000.onnx # more stable
# policy-2025-12-18_22-46-06-20000.onnx # remove gravity
rlagent:
  onnx_model_path: "policy/policy-2025-12-18_22-46-06-20000.onnx" # Path in ros package
  control_freq: 400.0
  decimation: 2
  ideal_obs: false
  ideal_obs_topic: "uav/cog/odom"
  ideal_delay: 0
  rlagent_verbose: false
  rlagent_debug: true
  rlagent_forward_info: true
  gimbal_target_delay_steps: 0
  gimbal_obs_delay_steps: 0
  enable_thrust: false
  thrust_scale: 1.0
  thrust_tau: 0.0
  thrust_target_delay_steps: 0
  enable_gimbal: false
  goal_pos_x: 0.0
  goal_pos_y: 0.0
  goal_pos_z: 0.9
  goal_angle_R: 0.0
  goal_angle_P: 0.0
  goal_angle_Y: 0.0
  thrust_default: 7.0
  gimbal_default: {gimbal1: 0.0, gimbal2: 0.0, gimbal3: 0.0, gimbal4: 0.0}
  gimbal_kp: 0.344964875
  gimbal_kd: 0.0094725 # 
  gimbal_effort_ctrl: false
  gimbal_size: 4
  thrust_size: 4
  scales:
    lin_vel: 1.0
    agn_vel: 0.2
    gimbal_act: 0.25
    thrust_act: 0.50
    clip_observation: 100.0
    clip_action: 100.0