aerial_robot_control_name: aerial_robot_control/beetle_pose_rlagent
# 1 roslaunch beetle_omni bringup_rl_omni.launch real_machine:=false simulation:=True headless:=False

# 2 aerial_robot_planning roscd python scripts/mpc_smach_node.py beetle1

# 3 100 sample waypoints experiments
# rosbag record -O 100samplesRL /beetle_omni/joint_states /beetle_omni/uav/cog/odom /beetle_omni/uav/baselink/odom /beetle_omni/ground_truth /desired_3D_pose /beetle_omni/four_axes/command /beetle_omni/observation_debug
# rosbag record -O 100samplesNMPC /beetle1/joint_states /beetle1/uav/cog/odom /beetle1/uav/baselink/odom /beetle1/ground_truth /beetle1/four_axes/command /beetle1/nmpc/viz_ref /beetle1/gimbals_ctrl

# policy-2026-01-09_20-11-41-20000.onnx benchmark
# policy-2026-01-23_20-34-47-20000.onnx: (looks nice)reset with reference, based on raw benchmark

# policy-2026-03-02_11-45-01-20000.onnx based on benchmark with beetle-rl urdf
# policy-2026-03-04_22-25-52-20000.onnx se3 env
# policy-2026-03-05_11-02-19-20000.onnx Omni env
# policy-2026-03-05_22-29-42-20000.onnx regoal with large vel penalty
# policy-2026-03-05_22-29-42-20000.onnx regoal and random gimbal

# rosservice call /beetle_omni/rlagent/reload_policy \
#   "policy_name: 'policy/policy-2026-03-05_22-29-42-20000.onnx'"

rlagent:
  onnx_model_path: "policy/policy-2026-03-06_13-37-13-16000.onnx" # Path in ros package
  control_freq: 400.0
  decimation: 2
  history_obs: false
  single_obs_size: 27
  history_length: 4
  fault_injection: true
  fault_obs: false
  fault_goal: false  # degraded goal when fault injected
  ideal_obs: false
  # ideal_obs_topic: "uav/cog/odom"
  ideal_obs_topic: "uav/baselink/odom"
  ideal_delay: 0
  fc2root_transform: true
  rlagent_verbose: false
  rlagent_debug: true
  rlagent_forward_info: true
  gimbal_target_delay_steps: 0
  gimbal_obs_delay_steps: 0
  enable_thrust: true
  thrust_scale: 1.0
  thrust_tau: 0.0 # 0.0342
  thrust_target_delay_steps: 1
  enable_gimbal: true
  goal_pos_x: 0.0
  goal_pos_y: 0.0
  goal_pos_z: 1.2
  goal_angle_R: 0.0
  goal_angle_P: 0.0
  goal_angle_Y: 0.0
  thrust_default: 7.0 # 6.0 before 3.
  thrust_limit: 20.0
  gimbal_default: {gimbal1: 0.0, gimbal2: 0.0, gimbal3: 0.0, gimbal4: 0.0}
  # gimbal_kp: 0.285
  # gimbal_kd: 0.019
  gimbal_kp: 0.344964875
  gimbal_kd: 0.0094725 # 
  gimbal_limit: 3.5 # rad
  gimbal_effort_ctrl: true
  gimbal_size: 4
  thrust_size: 4
  scales:
    lin_vel: 1.0
    agn_vel: 0.2
    gimbal_act: 0.25
    thrust_act: 0.50  # 1.25 before 3.
    clip_observation: 100.0
    clip_action: 100.0